-- ==========================================================
-- SCRIPT KHỞI TẠO CSDL TOÀN DIỆN CHO SUPABASE (RFID WMS SYSTEM)
-- Đầy đủ 100%: KHÓA CHÍNH (PK), KHÓA NGOẠI (FK), KHÁCH HÀNG, 
-- PHIẾU XUẤT HÀNG, KIỂM KÊ KHO, NGƯỜI DÙNG & REALTIME
-- ==========================================================

-- 1. Bảng Danh mục Sản phẩm (products)
CREATE TABLE IF NOT EXISTS public.products (
    product_id TEXT PRIMARY KEY,
    sku TEXT NOT NULL UNIQUE,
    product_name TEXT NOT NULL,
    unit TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Bảng Vị trí kho (locations)
CREATE TABLE IF NOT EXISTS public.locations (
    location_id TEXT PRIMARY KEY,
    location_code TEXT NOT NULL UNIQUE,
    zone TEXT NOT NULL,
    shelf TEXT NOT NULL,
    level TEXT NOT NULL,
    current_pallets INTEGER DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Bảng Pallet lưu kho (pallets)
-- FK: location_id -> locations(location_id)
CREATE TABLE IF NOT EXISTS public.pallets (
    pallet_id TEXT PRIMARY KEY,
    pallet_code TEXT NOT NULL UNIQUE,
    location_id TEXT REFERENCES public.locations (location_id) ON DELETE SET NULL,
    inbound_time TEXT NOT NULL,
    is_multi_sku INTEGER DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Bảng Mặt hàng cụ thể gắn thẻ RFID Chip (items)
-- FK: product_id -> products(product_id)
-- FK: pallet_id  -> pallets(pallet_id)
-- FK: location_id -> locations(location_id)
CREATE TABLE IF NOT EXISTS public.items (
    item_id TEXT PRIMARY KEY,
    product_id TEXT NOT NULL REFERENCES public.products (product_id) ON DELETE CASCADE,
    sku TEXT NOT NULL,
    product_name TEXT NOT NULL,
    serial_number TEXT NOT NULL,
    epc TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL,
    order_no TEXT,
    pallet_id TEXT REFERENCES public.pallets (pallet_id) ON DELETE SET NULL,
    location_id TEXT REFERENCES public.locations (location_id) ON DELETE SET NULL,
    inbound_time TEXT,
    allocated_time TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tạo Index để truy vấn thẻ RFID EPC và đơn hàng siêu nhanh
CREATE INDEX IF NOT EXISTS idx_items_epc ON public.items (epc);
CREATE INDEX IF NOT EXISTS idx_items_sku ON public.items (sku);
CREATE INDEX IF NOT EXISTS idx_items_status ON public.items (status);
CREATE INDEX IF NOT EXISTS idx_items_order_no ON public.items (order_no);
CREATE INDEX IF NOT EXISTS idx_items_pallet_id ON public.items (pallet_id);
CREATE INDEX IF NOT EXISTS idx_items_location_id ON public.items (location_id);

-- 5. Bảng Khách Hàng (customers)
CREATE TABLE IF NOT EXISTS public.customers (
    customer_id TEXT PRIMARY KEY,
    customer_code TEXT NOT NULL UNIQUE,
    customer_name TEXT NOT NULL,
    phone TEXT,
    email TEXT,
    address TEXT,
    tax_code TEXT,
    contact_person TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_customers_code ON public.customers (customer_code);

-- 6. Bảng Đơn Nhập kho (inbound_orders)
CREATE TABLE IF NOT EXISTS public.inbound_orders (
    inbound_order_id TEXT PRIMARY KEY,
    order_no TEXT NOT NULL UNIQUE,
    source_supplier TEXT NOT NULL,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Bảng Chi tiết Đơn Nhập (inbound_order_details)
-- FK: order_id -> inbound_orders(inbound_order_id)
-- FK: product_id -> products(product_id)
CREATE TABLE IF NOT EXISTS public.inbound_order_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id TEXT NOT NULL REFERENCES public.inbound_orders (inbound_order_id) ON DELETE CASCADE,
    product_id TEXT NOT NULL REFERENCES public.products (product_id) ON DELETE CASCADE,
    sku TEXT NOT NULL,
    product_name TEXT NOT NULL,
    required_qty INTEGER NOT NULL,
    received_qty INTEGER NOT NULL DEFAULT 0
);

-- 8. Bảng PO Đơn Xuất kho (outbound_orders)
CREATE TABLE IF NOT EXISTS public.outbound_orders (
    outbound_order_id TEXT PRIMARY KEY,
    po_no TEXT NOT NULL UNIQUE,
    customer TEXT NOT NULL,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. Bảng Chi tiết PO Đơn Xuất (outbound_order_details)
-- FK: order_id -> outbound_orders(outbound_order_id)
-- FK: product_id -> products(product_id)
CREATE TABLE IF NOT EXISTS public.outbound_order_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id TEXT NOT NULL REFERENCES public.outbound_orders (outbound_order_id) ON DELETE CASCADE,
    product_id TEXT NOT NULL REFERENCES public.products (product_id) ON DELETE CASCADE,
    sku TEXT NOT NULL,
    product_name TEXT NOT NULL,
    required_qty INTEGER NOT NULL,
    picked_qty INTEGER NOT NULL DEFAULT 0
);

-- 10. Bảng Phiếu Xuất Hàng / Vận Đơn (delivery_notes)
-- FK: customer_id -> customers(customer_id)
CREATE TABLE IF NOT EXISTS public.delivery_notes (
    delivery_id TEXT PRIMARY KEY,
    delivery_no TEXT NOT NULL UNIQUE,
    po_no TEXT,
    customer_id TEXT REFERENCES public.customers (customer_id) ON DELETE SET NULL,
    customer_name TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'DRAFT', -- 'DRAFT', 'PREPARED', 'SHIPPED', 'DELIVERED', 'CANCELLED'
    carrier TEXT,
    tracking_no TEXT,
    total_cartons INTEGER DEFAULT 0,
    total_qty INTEGER DEFAULT 0,
    created_by TEXT,
    shipped_at TIMESTAMPTZ,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_delivery_no ON public.delivery_notes (delivery_no);
CREATE INDEX IF NOT EXISTS idx_delivery_po ON public.delivery_notes (po_no);

-- 11. Bảng Chi tiết Phiếu Xuất Hàng (delivery_note_details)
-- FK: delivery_id -> delivery_notes(delivery_id)
-- FK: product_id -> products(product_id)
CREATE TABLE IF NOT EXISTS public.delivery_note_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_id TEXT NOT NULL REFERENCES public.delivery_notes (delivery_id) ON DELETE CASCADE,
    product_id TEXT NOT NULL REFERENCES public.products (product_id) ON DELETE CASCADE,
    sku TEXT NOT NULL,
    product_name TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    carton_code TEXT
);

-- 12. Bảng Phiên Kiểm Kê Kho (inventory_sessions)
CREATE TABLE IF NOT EXISTS public.inventory_sessions (
    session_id TEXT PRIMARY KEY,
    session_code TEXT NOT NULL UNIQUE,
    zone TEXT NOT NULL,
    location_code TEXT,
    started_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ,
    is_completed BOOLEAN DEFAULT FALSE,
    created_by TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_inventory_code ON public.inventory_sessions (session_code);

-- 13. Bảng Chi tiết Sai lệch Kiểm Kê (inventory_session_details)
-- FK: session_id -> inventory_sessions(session_id)
CREATE TABLE IF NOT EXISTS public.inventory_session_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES public.inventory_sessions (session_id) ON DELETE CASCADE,
    epc TEXT NOT NULL,
    sku TEXT,
    product_name TEXT,
    expected_location TEXT,
    actual_location TEXT,
    result_type TEXT NOT NULL, -- 'MATCH', 'MISSING', 'WRONG_LOCATION', 'UNKNOWN_EPC'
    read_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_inventory_det_session ON public.inventory_session_details (session_id);
CREATE INDEX IF NOT EXISTS idx_inventory_det_epc ON public.inventory_session_details (epc);

-- 14. Bảng Người dùng / Nhân viên kho (users)
CREATE TABLE IF NOT EXISTS public.users (
    user_id TEXT PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    full_name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    role TEXT NOT NULL DEFAULT 'operator', -- 'admin', 'manager', 'operator', 'forklift'
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_users_username ON public.users (username);

-- 15. Bảng Lịch sử Đồng bộ (sync_logs)
CREATE TABLE IF NOT EXISTS public.sync_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_id TEXT,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    action TEXT,
    table_name TEXT,
    record_count INTEGER,
    is_success BOOLEAN,
    message TEXT,
    device_info TEXT
);

-- 16. Bảng Cấu hình hệ thống (system_config)
CREATE TABLE IF NOT EXISTS public.system_config (
    config_key TEXT PRIMARY KEY,
    config_val TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================================
-- BẬT REALTIME AN TOÀN CHO CÁC BẢNG TRỌNG YẾU
-- ==========================================================
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    CREATE PUBLICATION supabase_realtime;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'products') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.products;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'items') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.items;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'pallets') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.pallets;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'inbound_orders') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.inbound_orders;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'inbound_order_details') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.inbound_order_details;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'outbound_orders') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.outbound_orders;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'outbound_order_details') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.outbound_order_details;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'locations') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.locations;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'customers') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.customers;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'delivery_notes') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.delivery_notes;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'delivery_note_details') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.delivery_note_details;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'inventory_sessions') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.inventory_sessions;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'inventory_session_details') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.inventory_session_details;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'users') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.users;
  END IF;
END $$;

-- ==========================================================
-- QUẢN LÝ QUYỀN TRUY CẬP (RLS)
-- Mở toàn quyền cho anon/authenticated API key
-- ==========================================================
ALTER TABLE public.products DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.locations DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.pallets DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.items DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.inbound_orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.inbound_order_details DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.outbound_orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.outbound_order_details DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.delivery_notes DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.delivery_note_details DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_session_details DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.sync_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_config DISABLE ROW LEVEL SECURITY;

DO $$
DECLARE
    tbl text;
BEGIN
    FOR tbl IN 
        SELECT tablename FROM pg_tables WHERE schemaname = 'public'
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS "Allow public all" ON public.%I', tbl);
        EXECUTE format('CREATE POLICY "Allow public all" ON public.%I FOR ALL TO public USING (true) WITH CHECK (true)', tbl);
    END LOOP;
END $$;
