-- ==========================================================
-- SCRIPT KHỞI TẠO CSDL TOÀN DIỆN CHO SUPABASE (RFID WMS SYSTEM)
-- Đầy đủ 100%: KHÓA CHÍNH (PK), KHÓA NGOẠI (FK), KHÁCH HÀNG, 
-- PHIẾU XUẤT HÀNG, KIỂM KÊ KHO, NGƯỜI DÙNG & REALTIME
-- ==========================================================

-- 1. Bảng Danh mục Sản phẩm (products)
CREATE TABLE IF NOT EXISTS public.products (
    product_id TEXT PRIMARY KEY,
    sku TEXT NOT NULL UNIQUE,
    product_name TEXT NOT NULL,
    unit TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Bảng Vị trí kho (locations)
CREATE TABLE IF NOT EXISTS public.locations (
    location_id TEXT PRIMARY KEY,
    location_code TEXT NOT NULL UNIQUE,
    zone TEXT NOT NULL,
    shelf TEXT NOT NULL,
    level TEXT NOT NULL,
    current_pallets INTEGER DEFAULT 0,
    status TEXT DEFAULT 'AVAILABLE',
    max_pallet_capacity INTEGER DEFAULT 1,
    aisle_side TEXT DEFAULT 'LEFT',
    sort_order INTEGER DEFAULT 0,
    grid_row INTEGER DEFAULT 0,
    grid_col INTEGER DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.locations ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'AVAILABLE';
ALTER TABLE public.locations ADD COLUMN IF NOT EXISTS max_pallet_capacity INTEGER DEFAULT 1;
ALTER TABLE public.locations ADD COLUMN IF NOT EXISTS aisle_side TEXT DEFAULT 'LEFT';
ALTER TABLE public.locations ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0;
ALTER TABLE public.locations ADD COLUMN IF NOT EXISTS grid_row INTEGER DEFAULT 0;
ALTER TABLE public.locations ADD COLUMN IF NOT EXISTS grid_col INTEGER DEFAULT 0;

-- 3. Bảng Pallet lưu kho (pallets)
-- FK: location_id -> locations(location_id)
CREATE TABLE IF NOT EXISTS public.pallets (
    pallet_id TEXT PRIMARY KEY,
    pallet_code TEXT NOT NULL UNIQUE,
    rfid_epc TEXT,
    location_id TEXT REFERENCES public.locations (location_id) ON DELETE SET NULL,
    inbound_time TEXT NOT NULL,
    is_multi_sku INTEGER DEFAULT 0,
    placed_by TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.pallets ADD COLUMN IF NOT EXISTS rfid_epc TEXT;
ALTER TABLE public.pallets ADD COLUMN IF NOT EXISTS placed_by TEXT;
ALTER TABLE public.pallets ADD COLUMN IF NOT EXISTS pallet_name TEXT;

-- 4. Bảng Mặt hàng cụ thể gắn thẻ RFID Chip (items)
-- FK: product_id -> products(product_id)
-- FK: pallet_id  -> pallets(pallet_id)
-- FK: location_id -> locations(location_id)
CREATE TABLE IF NOT EXISTS public.items (
    item_id TEXT PRIMARY KEY,
    product_id TEXT NOT NULL REFERENCES public.products (product_id) ON DELETE CASCADE,
    sku TEXT NOT NULL,
    product_name TEXT NOT NULL,
    serial_number TEXT NOT NULL,
    epc TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL,
    order_no TEXT,
    pallet_id TEXT REFERENCES public.pallets (pallet_id) ON DELETE SET NULL,
    location_id TEXT REFERENCES public.locations (location_id) ON DELETE SET NULL,
    inbound_time TEXT,
    allocated_time TEXT,
    supplier TEXT,
    carton_code TEXT,
    inbound_by TEXT,
    putaway_by TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.items ADD COLUMN IF NOT EXISTS carton_code TEXT;
ALTER TABLE public.items ADD COLUMN IF NOT EXISTS supplier TEXT;
ALTER TABLE public.items ADD COLUMN IF NOT EXISTS inbound_by TEXT;
ALTER TABLE public.items ADD COLUMN IF NOT EXISTS putaway_by TEXT;

-- Tạo Index để truy vấn thẻ RFID EPC và đơn hàng siêu nhanh
CREATE INDEX IF NOT EXISTS idx_items_epc ON public.items (epc);
CREATE INDEX IF NOT EXISTS idx_items_sku ON public.items (sku);
CREATE INDEX IF NOT EXISTS idx_items_status ON public.items (status);
CREATE INDEX IF NOT EXISTS idx_items_order_no ON public.items (order_no);
CREATE INDEX IF NOT EXISTS idx_items_pallet_id ON public.items (pallet_id);
CREATE INDEX IF NOT EXISTS idx_items_location_id ON public.items (location_id);

-- 5. Bảng Khách Hàng (customers)
CREATE TABLE IF NOT EXISTS public.customers (
    customer_id TEXT PRIMARY KEY,
    customer_code TEXT NOT NULL UNIQUE,
    customer_name TEXT NOT NULL,
    phone TEXT,
    email TEXT,
    address TEXT,
    tax_code TEXT,
    contact_person TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_customers_code ON public.customers (customer_code);

-- 6. Bảng Đơn Nhập kho (inbound_orders)
CREATE TABLE IF NOT EXISTS public.inbound_orders (
    inbound_order_id TEXT PRIMARY KEY,
    order_no TEXT NOT NULL UNIQUE,
    source_supplier TEXT NOT NULL,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Bảng Chi tiết Đơn Nhập (inbound_order_details)
-- FK: order_id -> inbound_orders(inbound_order_id)
-- FK: product_id -> products(product_id)
CREATE TABLE IF NOT EXISTS public.inbound_order_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id TEXT NOT NULL REFERENCES public.inbound_orders (inbound_order_id) ON DELETE CASCADE,
    product_id TEXT NOT NULL REFERENCES public.products (product_id) ON DELETE CASCADE,
    sku TEXT NOT NULL,
    product_name TEXT NOT NULL,
    required_qty INTEGER NOT NULL,
    received_qty INTEGER NOT NULL DEFAULT 0
);

-- 8. Bảng PO Đơn Xuất kho (outbound_orders)
CREATE TABLE IF NOT EXISTS public.outbound_orders (
    outbound_order_id TEXT PRIMARY KEY,
    po_no TEXT NOT NULL UNIQUE,
    customer TEXT NOT NULL,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. Bảng Chi tiết PO Đơn Xuất (outbound_order_details)
-- FK: order_id -> outbound_orders(outbound_order_id)
-- FK: product_id -> products(product_id)
CREATE TABLE IF NOT EXISTS public.outbound_order_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id TEXT NOT NULL REFERENCES public.outbound_orders (outbound_order_id) ON DELETE CASCADE,
    product_id TEXT NOT NULL REFERENCES public.products (product_id) ON DELETE CASCADE,
    sku TEXT NOT NULL,
    product_name TEXT NOT NULL,
    required_qty INTEGER NOT NULL,
    picked_qty INTEGER NOT NULL DEFAULT 0
);

-- 10. Bảng Phiếu Xuất Hàng / Vận Đơn (delivery_notes)
-- FK: customer_id -> customers(customer_id)
CREATE TABLE IF NOT EXISTS public.delivery_notes (
    delivery_id TEXT PRIMARY KEY,
    delivery_no TEXT NOT NULL UNIQUE,
    po_no TEXT,
    customer_id TEXT REFERENCES public.customers (customer_id) ON DELETE SET NULL,
    customer_name TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'DRAFT', -- 'DRAFT', 'PREPARED', 'SHIPPED', 'DELIVERED', 'CANCELLED'
    carrier TEXT,
    tracking_no TEXT,
    total_cartons INTEGER DEFAULT 0,
    total_qty INTEGER DEFAULT 0,
    created_by TEXT,
    shipped_at TIMESTAMPTZ,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_delivery_no ON public.delivery_notes (delivery_no);
CREATE INDEX IF NOT EXISTS idx_delivery_po ON public.delivery_notes (po_no);

-- 11. Bảng Chi tiết Phiếu Xuất Hàng (delivery_note_details)
-- FK: delivery_id -> delivery_notes(delivery_id)
-- FK: product_id -> products(product_id)
CREATE TABLE IF NOT EXISTS public.delivery_note_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_id TEXT NOT NULL REFERENCES public.delivery_notes (delivery_id) ON DELETE CASCADE,
    product_id TEXT NOT NULL REFERENCES public.products (product_id) ON DELETE CASCADE,
    sku TEXT NOT NULL,
    product_name TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    carton_code TEXT
);

-- 12. Bảng Phiên Kiểm Kê Kho (inventory_sessions)
CREATE TABLE IF NOT EXISTS public.inventory_sessions (
    session_id TEXT PRIMARY KEY,
    session_code TEXT NOT NULL UNIQUE,
    zone TEXT NOT NULL,
    location_code TEXT,
    started_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ,
    is_completed BOOLEAN DEFAULT FALSE,
    created_by TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_inventory_code ON public.inventory_sessions (session_code);

-- 13. Bảng Chi tiết Sai lệch Kiểm Kê (inventory_session_details)
-- FK: session_id -> inventory_sessions(session_id)
CREATE TABLE IF NOT EXISTS public.inventory_session_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES public.inventory_sessions (session_id) ON DELETE CASCADE,
    epc TEXT NOT NULL,
    sku TEXT,
    product_name TEXT,
    expected_location TEXT,
    actual_location TEXT,
    result_type TEXT NOT NULL, -- 'MATCH', 'MISSING', 'WRONG_LOCATION', 'UNKNOWN_EPC'
    read_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_inventory_det_session ON public.inventory_session_details (session_id);
CREATE INDEX IF NOT EXISTS idx_inventory_det_epc ON public.inventory_session_details (epc);

-- 14. Bảng Người dùng / Nhân viên kho (users)
CREATE TABLE IF NOT EXISTS public.users (
    user_id TEXT PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    full_name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    role TEXT NOT NULL DEFAULT 'thukho', -- 'admin', 'kythuat', 'thukho', 'handheld', 'seller'
    password_hash TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS password_hash TEXT;
CREATE INDEX IF NOT EXISTS idx_users_username ON public.users (username);

-- 15. Bảng Lịch sử Đồng bộ (sync_logs)
CREATE TABLE IF NOT EXISTS public.sync_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_id TEXT,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    action TEXT,
    table_name TEXT,
    record_count INTEGER,
    is_success BOOLEAN,
    message TEXT,
    device_info TEXT
);

-- 16. Bảng Cấu hình hệ thống (system_config)
CREATE TABLE IF NOT EXISTS public.system_config (
    config_key TEXT PRIMARY KEY,
    config_val TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 17. Bảng Lịch sử Biến động Kho Nghiệp vụ (inventory_transactions)
CREATE TABLE IF NOT EXISTS public.inventory_transactions (
    transaction_id TEXT NOT NULL PRIMARY KEY,
    transaction_type TEXT NOT NULL,
    document_no TEXT,
    sku TEXT,
    product_name TEXT,
    quantity INTEGER NOT NULL DEFAULT 1,
    from_location TEXT,
    to_location TEXT,
    pallet_code TEXT,
    performed_by TEXT,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_inventory_transactions_type ON public.inventory_transactions (transaction_type);
CREATE INDEX IF NOT EXISTS idx_inventory_transactions_doc ON public.inventory_transactions (document_no);
CREATE INDEX IF NOT EXISTS idx_inventory_transactions_pallet ON public.inventory_transactions (pallet_code);
CREATE INDEX IF NOT EXISTS idx_inventory_transactions_timestamp ON public.inventory_transactions (timestamp DESC);


-- ==========================================================
-- BỔ SUNG & ĐỒNG BỘ TOÀN BỘ KHÓA CHÍNH (PK) & KHÓA NGOẠI (FK)
-- ==========================================================

-- 1. Thiết lập Khóa Chính (Primary Keys - PK) an toàn cho toàn bộ 16 bảng
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.products'::regclass AND contype = 'p') THEN
        ALTER TABLE public.products ALTER COLUMN product_id SET NOT NULL;
        ALTER TABLE public.products ADD CONSTRAINT pk_products PRIMARY KEY (product_id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.locations'::regclass AND contype = 'p') THEN
        ALTER TABLE public.locations ALTER COLUMN location_id SET NOT NULL;
        ALTER TABLE public.locations ADD CONSTRAINT pk_locations PRIMARY KEY (location_id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.pallets'::regclass AND contype = 'p') THEN
        ALTER TABLE public.pallets ALTER COLUMN pallet_id SET NOT NULL;
        ALTER TABLE public.pallets ADD CONSTRAINT pk_pallets PRIMARY KEY (pallet_id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.items'::regclass AND contype = 'p') THEN
        ALTER TABLE public.items ALTER COLUMN item_id SET NOT NULL;
        ALTER TABLE public.items ADD CONSTRAINT pk_items PRIMARY KEY (item_id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.customers'::regclass AND contype = 'p') THEN
        ALTER TABLE public.customers ALTER COLUMN customer_id SET NOT NULL;
        ALTER TABLE public.customers ADD CONSTRAINT pk_customers PRIMARY KEY (customer_id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.inbound_orders'::regclass AND contype = 'p') THEN
        ALTER TABLE public.inbound_orders ALTER COLUMN inbound_order_id SET NOT NULL;
        ALTER TABLE public.inbound_orders ADD CONSTRAINT pk_inbound_orders PRIMARY KEY (inbound_order_id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.inbound_order_details'::regclass AND contype = 'p') THEN
        ALTER TABLE public.inbound_order_details ALTER COLUMN id SET NOT NULL;
        ALTER TABLE public.inbound_order_details ADD CONSTRAINT pk_inbound_order_details PRIMARY KEY (id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.outbound_orders'::regclass AND contype = 'p') THEN
        ALTER TABLE public.outbound_orders ALTER COLUMN outbound_order_id SET NOT NULL;
        ALTER TABLE public.outbound_orders ADD CONSTRAINT pk_outbound_orders PRIMARY KEY (outbound_order_id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.outbound_order_details'::regclass AND contype = 'p') THEN
        ALTER TABLE public.outbound_order_details ALTER COLUMN id SET NOT NULL;
        ALTER TABLE public.outbound_order_details ADD CONSTRAINT pk_outbound_order_details PRIMARY KEY (id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.delivery_notes'::regclass AND contype = 'p') THEN
        ALTER TABLE public.delivery_notes ALTER COLUMN delivery_id SET NOT NULL;
        ALTER TABLE public.delivery_notes ADD CONSTRAINT pk_delivery_notes PRIMARY KEY (delivery_id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.delivery_note_details'::regclass AND contype = 'p') THEN
        ALTER TABLE public.delivery_note_details ALTER COLUMN id SET NOT NULL;
        ALTER TABLE public.delivery_note_details ADD CONSTRAINT pk_delivery_note_details PRIMARY KEY (id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.inventory_sessions'::regclass AND contype = 'p') THEN
        ALTER TABLE public.inventory_sessions ALTER COLUMN session_id SET NOT NULL;
        ALTER TABLE public.inventory_sessions ADD CONSTRAINT pk_inventory_sessions PRIMARY KEY (session_id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.inventory_session_details'::regclass AND contype = 'p') THEN
        ALTER TABLE public.inventory_session_details ALTER COLUMN id SET NOT NULL;
        ALTER TABLE public.inventory_session_details ADD CONSTRAINT pk_inventory_session_details PRIMARY KEY (id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.users'::regclass AND contype = 'p') THEN
        ALTER TABLE public.users ALTER COLUMN user_id SET NOT NULL;
        ALTER TABLE public.users ADD CONSTRAINT pk_users PRIMARY KEY (user_id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.sync_logs'::regclass AND contype = 'p') THEN
        ALTER TABLE public.sync_logs ALTER COLUMN id SET NOT NULL;
        ALTER TABLE public.sync_logs ADD CONSTRAINT pk_sync_logs PRIMARY KEY (id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.system_config'::regclass AND contype = 'p') THEN
        ALTER TABLE public.system_config ALTER COLUMN config_key SET NOT NULL;
        ALTER TABLE public.system_config ADD CONSTRAINT pk_system_config PRIMARY KEY (config_key);
    END IF;
END $$;

-- 2. Thiết lập Ràng buộc Duy nhất (Unique Constraints - UK) cho các cột tham chiếu
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint c WHERE c.conrelid = 'public.locations'::regclass AND c.contype IN ('u', 'p') AND EXISTS (SELECT 1 FROM pg_attribute a WHERE a.attrelid = c.conrelid AND a.attnum = ANY(c.conkey) AND a.attname = 'location_code')) THEN
        ALTER TABLE public.locations ADD CONSTRAINT uq_locations_location_code UNIQUE (location_code);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint c WHERE c.conrelid = 'public.outbound_orders'::regclass AND c.contype IN ('u', 'p') AND EXISTS (SELECT 1 FROM pg_attribute a WHERE a.attrelid = c.conrelid AND a.attnum = ANY(c.conkey) AND a.attname = 'po_no')) THEN
        ALTER TABLE public.outbound_orders ADD CONSTRAINT uq_outbound_orders_po_no UNIQUE (po_no);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint c WHERE c.conrelid = 'public.products'::regclass AND c.contype IN ('u', 'p') AND EXISTS (SELECT 1 FROM pg_attribute a WHERE a.attrelid = c.conrelid AND a.attnum = ANY(c.conkey) AND a.attname = 'sku')) THEN
        ALTER TABLE public.products ADD CONSTRAINT uq_products_sku UNIQUE (sku);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint c WHERE c.conrelid = 'public.pallets'::regclass AND c.contype IN ('u', 'p') AND EXISTS (SELECT 1 FROM pg_attribute a WHERE a.attrelid = c.conrelid AND a.attnum = ANY(c.conkey) AND a.attname = 'pallet_code')) THEN
        ALTER TABLE public.pallets ADD CONSTRAINT uq_pallets_pallet_code UNIQUE (pallet_code);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint c WHERE c.conrelid = 'public.items'::regclass AND c.contype IN ('u', 'p') AND EXISTS (SELECT 1 FROM pg_attribute a WHERE a.attrelid = c.conrelid AND a.attnum = ANY(c.conkey) AND a.attname = 'epc')) THEN
        ALTER TABLE public.items ADD CONSTRAINT uq_items_epc UNIQUE (epc);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint c WHERE c.conrelid = 'public.customers'::regclass AND c.contype IN ('u', 'p') AND EXISTS (SELECT 1 FROM pg_attribute a WHERE a.attrelid = c.conrelid AND a.attnum = ANY(c.conkey) AND a.attname = 'customer_code')) THEN
        ALTER TABLE public.customers ADD CONSTRAINT uq_customers_customer_code UNIQUE (customer_code);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint c WHERE c.conrelid = 'public.inbound_orders'::regclass AND c.contype IN ('u', 'p') AND EXISTS (SELECT 1 FROM pg_attribute a WHERE a.attrelid = c.conrelid AND a.attnum = ANY(c.conkey) AND a.attname = 'order_no')) THEN
        ALTER TABLE public.inbound_orders ADD CONSTRAINT uq_inbound_orders_order_no UNIQUE (order_no);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint c WHERE c.conrelid = 'public.delivery_notes'::regclass AND c.contype IN ('u', 'p') AND EXISTS (SELECT 1 FROM pg_attribute a WHERE a.attrelid = c.conrelid AND a.attnum = ANY(c.conkey) AND a.attname = 'delivery_no')) THEN
        ALTER TABLE public.delivery_notes ADD CONSTRAINT uq_delivery_notes_delivery_no UNIQUE (delivery_no);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint c WHERE c.conrelid = 'public.inventory_sessions'::regclass AND c.contype IN ('u', 'p') AND EXISTS (SELECT 1 FROM pg_attribute a WHERE a.attrelid = c.conrelid AND a.attnum = ANY(c.conkey) AND a.attname = 'session_code')) THEN
        ALTER TABLE public.inventory_sessions ADD CONSTRAINT uq_inventory_sessions_session_code UNIQUE (session_code);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint c WHERE c.conrelid = 'public.users'::regclass AND c.contype IN ('u', 'p') AND EXISTS (SELECT 1 FROM pg_attribute a WHERE a.attrelid = c.conrelid AND a.attnum = ANY(c.conkey) AND a.attname = 'username')) THEN
        ALTER TABLE public.users ADD CONSTRAINT uq_users_username UNIQUE (username);
    END IF;
END $$;

-- 3. Chuẩn hóa dữ liệu mồ côi (Orphan Cleanup) trước khi gán FK
DO $$
BEGIN
    UPDATE public.pallets 
    SET location_id = NULL 
    WHERE location_id IS NOT NULL 
      AND location_id NOT IN (SELECT location_id FROM public.locations);

    UPDATE public.items 
    SET pallet_id = NULL 
    WHERE pallet_id IS NOT NULL 
      AND pallet_id NOT IN (SELECT pallet_id FROM public.pallets);

    UPDATE public.items 
    SET location_id = NULL 
    WHERE location_id IS NOT NULL 
      AND location_id NOT IN (SELECT location_id FROM public.locations);

    INSERT INTO public.products (product_id, sku, product_name, unit, category, description)
    SELECT DISTINCT i.product_id, i.sku, i.product_name, 'Cái', 'Hàng hoá', 'Tự động tạo từ Item'
    FROM public.items i
    WHERE i.product_id IS NOT NULL 
      AND i.product_id NOT IN (SELECT product_id FROM public.products)
    ON CONFLICT (product_id) DO NOTHING;

    DELETE FROM public.inbound_order_details
    WHERE order_id NOT IN (SELECT inbound_order_id FROM public.inbound_orders);

    INSERT INTO public.products (product_id, sku, product_name, unit, category, description)
    SELECT DISTINCT iod.product_id, iod.sku, iod.product_name, 'Cái', 'Hàng hoá', 'Tự động tạo từ Đơn Nhập'
    FROM public.inbound_order_details iod
    WHERE iod.product_id IS NOT NULL 
      AND iod.product_id NOT IN (SELECT product_id FROM public.products)
    ON CONFLICT (product_id) DO NOTHING;

    DELETE FROM public.outbound_order_details
    WHERE order_id NOT IN (SELECT outbound_order_id FROM public.outbound_orders);

    INSERT INTO public.products (product_id, sku, product_name, unit, category, description)
    SELECT DISTINCT ood.product_id, ood.sku, ood.product_name, 'Cái', 'Hàng hoá', 'Tự động tạo từ Đơn Xuất'
    FROM public.outbound_order_details ood
    WHERE ood.product_id IS NOT NULL 
      AND ood.product_id NOT IN (SELECT product_id FROM public.products)
    ON CONFLICT (product_id) DO NOTHING;

    UPDATE public.delivery_notes 
    SET customer_id = NULL 
    WHERE customer_id IS NOT NULL 
      AND customer_id NOT IN (SELECT customer_id FROM public.customers);

    UPDATE public.delivery_notes 
    SET po_no = NULL 
    WHERE po_no IS NOT NULL 
      AND po_no NOT IN (SELECT po_no FROM public.outbound_orders);

    DELETE FROM public.delivery_note_details
    WHERE delivery_id NOT IN (SELECT delivery_id FROM public.delivery_notes);

    INSERT INTO public.products (product_id, sku, product_name, unit, category, description)
    SELECT DISTINCT dnd.product_id, dnd.sku, dnd.product_name, 'Cái', 'Hàng hoá', 'Tự động tạo từ Phiếu Xuất'
    FROM public.delivery_note_details dnd
    WHERE dnd.product_id IS NOT NULL 
      AND dnd.product_id NOT IN (SELECT product_id FROM public.products)
    ON CONFLICT (product_id) DO NOTHING;

    UPDATE public.inventory_sessions 
    SET location_code = NULL 
    WHERE location_code IS NOT NULL 
      AND location_code NOT IN (SELECT location_code FROM public.locations);

    DELETE FROM public.inventory_session_details
    WHERE session_id NOT IN (SELECT session_id FROM public.inventory_sessions);
END $$;

-- 2. Thiết lập ràng buộc Khóa Ngoại (Foreign Key Constraints)
DO $$
BEGIN
    -- FK 1: pallets -> locations
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_pallets_location') THEN
        ALTER TABLE public.pallets
        ADD CONSTRAINT fk_pallets_location
        FOREIGN KEY (location_id) REFERENCES public.locations (location_id)
        ON DELETE SET NULL ON UPDATE CASCADE;
    END IF;

    -- FK 2: items -> products
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_items_product') THEN
        ALTER TABLE public.items
        ADD CONSTRAINT fk_items_product
        FOREIGN KEY (product_id) REFERENCES public.products (product_id)
        ON DELETE CASCADE ON UPDATE CASCADE;
    END IF;

    -- FK 3: items -> pallets
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_items_pallet') THEN
        ALTER TABLE public.items
        ADD CONSTRAINT fk_items_pallet
        FOREIGN KEY (pallet_id) REFERENCES public.pallets (pallet_id)
        ON DELETE SET NULL ON UPDATE CASCADE;
    END IF;

    -- FK 4: items -> locations
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_items_location') THEN
        ALTER TABLE public.items
        ADD CONSTRAINT fk_items_location
        FOREIGN KEY (location_id) REFERENCES public.locations (location_id)
        ON DELETE SET NULL ON UPDATE CASCADE;
    END IF;

    -- FK 5: inbound_order_details -> inbound_orders
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_inbound_order_details_order') THEN
        ALTER TABLE public.inbound_order_details
        ADD CONSTRAINT fk_inbound_order_details_order
        FOREIGN KEY (order_id) REFERENCES public.inbound_orders (inbound_order_id)
        ON DELETE CASCADE ON UPDATE CASCADE;
    END IF;

    -- FK 6: inbound_order_details -> products
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_inbound_order_details_product') THEN
        ALTER TABLE public.inbound_order_details
        ADD CONSTRAINT fk_inbound_order_details_product
        FOREIGN KEY (product_id) REFERENCES public.products (product_id)
        ON DELETE CASCADE ON UPDATE CASCADE;
    END IF;

    -- FK 7: outbound_order_details -> outbound_orders
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_outbound_order_details_order') THEN
        ALTER TABLE public.outbound_order_details
        ADD CONSTRAINT fk_outbound_order_details_order
        FOREIGN KEY (order_id) REFERENCES public.outbound_orders (outbound_order_id)
        ON DELETE CASCADE ON UPDATE CASCADE;
    END IF;

    -- FK 8: outbound_order_details -> products
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_outbound_order_details_product') THEN
        ALTER TABLE public.outbound_order_details
        ADD CONSTRAINT fk_outbound_order_details_product
        FOREIGN KEY (product_id) REFERENCES public.products (product_id)
        ON DELETE CASCADE ON UPDATE CASCADE;
    END IF;

    -- FK 9: delivery_notes -> customers
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_delivery_notes_customer') THEN
        ALTER TABLE public.delivery_notes
        ADD CONSTRAINT fk_delivery_notes_customer
        FOREIGN KEY (customer_id) REFERENCES public.customers (customer_id)
        ON DELETE SET NULL ON UPDATE CASCADE;
    END IF;

    -- FK 10: delivery_notes -> outbound_orders
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_delivery_notes_po') THEN
        ALTER TABLE public.delivery_notes
        ADD CONSTRAINT fk_delivery_notes_po
        FOREIGN KEY (po_no) REFERENCES public.outbound_orders (po_no)
        ON DELETE SET NULL ON UPDATE CASCADE;
    END IF;

    -- FK 11: delivery_note_details -> delivery_notes
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_delivery_note_details_delivery') THEN
        ALTER TABLE public.delivery_note_details
        ADD CONSTRAINT fk_delivery_note_details_delivery
        FOREIGN KEY (delivery_id) REFERENCES public.delivery_notes (delivery_id)
        ON DELETE CASCADE ON UPDATE CASCADE;
    END IF;

    -- FK 12: delivery_note_details -> products
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_delivery_note_details_product') THEN
        ALTER TABLE public.delivery_note_details
        ADD CONSTRAINT fk_delivery_note_details_product
        FOREIGN KEY (product_id) REFERENCES public.products (product_id)
        ON DELETE CASCADE ON UPDATE CASCADE;
    END IF;

    -- FK 13: inventory_sessions -> locations
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_inventory_sessions_location') THEN
        ALTER TABLE public.inventory_sessions
        ADD CONSTRAINT fk_inventory_sessions_location
        FOREIGN KEY (location_code) REFERENCES public.locations (location_code)
        ON DELETE SET NULL ON UPDATE CASCADE;
    END IF;

    -- FK 14: inventory_session_details -> inventory_sessions
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_inventory_session_details_session') THEN
        ALTER TABLE public.inventory_session_details
        ADD CONSTRAINT fk_inventory_session_details_session
        FOREIGN KEY (session_id) REFERENCES public.inventory_sessions (session_id)
        ON DELETE CASCADE ON UPDATE CASCADE;
    END IF;
END $$;

-- 3. Tạo Indexes cho toàn bộ các cột Khóa Ngoại
CREATE INDEX IF NOT EXISTS idx_pallets_location_id ON public.pallets (location_id);
CREATE INDEX IF NOT EXISTS idx_items_product_id ON public.items (product_id);
CREATE INDEX IF NOT EXISTS idx_items_pallet_id ON public.items (pallet_id);
CREATE INDEX IF NOT EXISTS idx_items_location_id ON public.items (location_id);
CREATE INDEX IF NOT EXISTS idx_inbound_order_details_order_id ON public.inbound_order_details (order_id);
CREATE INDEX IF NOT EXISTS idx_inbound_order_details_product_id ON public.inbound_order_details (product_id);
CREATE INDEX IF NOT EXISTS idx_outbound_order_details_order_id ON public.outbound_order_details (order_id);
CREATE INDEX IF NOT EXISTS idx_outbound_order_details_product_id ON public.outbound_order_details (product_id);
CREATE INDEX IF NOT EXISTS idx_delivery_notes_customer_id ON public.delivery_notes (customer_id);
CREATE INDEX IF NOT EXISTS idx_delivery_notes_po_no ON public.delivery_notes (po_no);
CREATE INDEX IF NOT EXISTS idx_delivery_note_details_delivery_id ON public.delivery_note_details (delivery_id);
CREATE INDEX IF NOT EXISTS idx_delivery_note_details_product_id ON public.delivery_note_details (product_id);
CREATE INDEX IF NOT EXISTS idx_inventory_sessions_location_code ON public.inventory_sessions (location_code);
CREATE INDEX IF NOT EXISTS idx_inventory_session_details_session_id ON public.inventory_session_details (session_id);

-- ==========================================================
-- BẬT REALTIME AN TOÀN CHO CÁC BẢNG TRỌNG YẾU
-- ==========================================================
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    CREATE PUBLICATION supabase_realtime;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'products') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.products;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'items') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.items;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'pallets') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.pallets;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'inbound_orders') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.inbound_orders;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'inbound_order_details') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.inbound_order_details;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'outbound_orders') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.outbound_orders;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'outbound_order_details') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.outbound_order_details;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'locations') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.locations;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'customers') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.customers;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'delivery_notes') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.delivery_notes;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'delivery_note_details') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.delivery_note_details;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'inventory_sessions') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.inventory_sessions;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'inventory_session_details') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.inventory_session_details;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'users') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.users;
  END IF;
END $$;

-- ==========================================================
-- QUẢN LÝ QUYỀN TRUY CẬP (RLS)
-- Mở toàn quyền cho anon/authenticated API key
-- ==========================================================
ALTER TABLE public.products DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.locations DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.pallets DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.items DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.inbound_orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.inbound_order_details DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.outbound_orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.outbound_order_details DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.delivery_notes DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.delivery_note_details DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_session_details DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.sync_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_config DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_transactions DISABLE ROW LEVEL SECURITY;


DO $$
DECLARE
    tbl text;
BEGIN
    FOR tbl IN 
        SELECT tablename FROM pg_tables WHERE schemaname = 'public'
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS "Allow public all" ON public.%I', tbl);
        EXECUTE format('CREATE POLICY "Allow public all" ON public.%I FOR ALL TO public USING (true) WITH CHECK (true)', tbl);
    END LOOP;
END $$;
