-- ==========================================================
-- SCRIPT KHỞI TẠO CSDL CHO SUPABASE (RFID WMS SYSTEM)
-- Copy toàn bộ đoạn script này và dán vào Supabase SQL Editor -> Bấm RUN
-- ==========================================================

-- 1. Bảng Danh mục Sản phẩm (products)
CREATE TABLE IF NOT EXISTS public.products (
    product_id TEXT PRIMARY KEY,
    sku TEXT NOT NULL UNIQUE,
    product_name TEXT NOT NULL,
    unit TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Bảng Vị trí kho (locations)
CREATE TABLE IF NOT EXISTS public.locations (
    location_id TEXT PRIMARY KEY,
    location_code TEXT NOT NULL UNIQUE,
    zone TEXT NOT NULL,
    shelf TEXT NOT NULL,
    level TEXT NOT NULL,
    current_pallets INTEGER DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Bảng Pallet lưu kho (pallets)
CREATE TABLE IF NOT EXISTS public.pallets (
    pallet_id TEXT PRIMARY KEY,
    pallet_code TEXT NOT NULL UNIQUE,
    location_id TEXT,
    inbound_time TEXT NOT NULL,
    is_multi_sku INTEGER DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Bảng Mặt hàng cụ thể gắn thẻ RFID Chip (items)
CREATE TABLE IF NOT EXISTS public.items (
    item_id TEXT PRIMARY KEY,
    product_id TEXT NOT NULL,
    sku TEXT NOT NULL,
    product_name TEXT NOT NULL,
    serial_number TEXT NOT NULL,
    epc TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL,
    order_no TEXT,
    pallet_id TEXT,
    location_id TEXT,
    inbound_time TEXT,
    allocated_time TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tạo Index để truy vấn thẻ RFID EPC và đơn hàng siêu nhanh
CREATE INDEX IF NOT EXISTS idx_items_epc ON public.items (epc);
CREATE INDEX IF NOT EXISTS idx_items_sku ON public.items (sku);
CREATE INDEX IF NOT EXISTS idx_items_status ON public.items (status);
CREATE INDEX IF NOT EXISTS idx_items_order_no ON public.items (order_no);
CREATE INDEX IF NOT EXISTS idx_items_pallet_id ON public.items (pallet_id);
CREATE INDEX IF NOT EXISTS idx_items_location_id ON public.items (location_id);

-- 5. Bảng Đơn Nhập kho (inbound_orders)
CREATE TABLE IF NOT EXISTS public.inbound_orders (
    inbound_order_id TEXT PRIMARY KEY,
    order_no TEXT NOT NULL UNIQUE,
    source_supplier TEXT NOT NULL,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Bảng Chi tiết Đơn Nhập (inbound_order_details)
CREATE TABLE IF NOT EXISTS public.inbound_order_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id TEXT NOT NULL REFERENCES public.inbound_orders (inbound_order_id) ON DELETE CASCADE,
    product_id TEXT NOT NULL,
    sku TEXT NOT NULL,
    product_name TEXT NOT NULL,
    required_qty INTEGER NOT NULL,
    received_qty INTEGER NOT NULL DEFAULT 0
);

-- 7. Bảng PO Đơn Xuất kho (outbound_orders)
CREATE TABLE IF NOT EXISTS public.outbound_orders (
    outbound_order_id TEXT PRIMARY KEY,
    po_no TEXT NOT NULL UNIQUE,
    customer TEXT NOT NULL,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Bảng Chi tiết PO Đơn Xuất (outbound_order_details)
CREATE TABLE IF NOT EXISTS public.outbound_order_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id TEXT NOT NULL REFERENCES public.outbound_orders (outbound_order_id) ON DELETE CASCADE,
    product_id TEXT NOT NULL,
    sku TEXT NOT NULL,
    product_name TEXT NOT NULL,
    required_qty INTEGER NOT NULL,
    picked_qty INTEGER NOT NULL DEFAULT 0
);

-- 9. Bảng Lịch sử Đồng bộ (sync_logs)
CREATE TABLE IF NOT EXISTS public.sync_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_id TEXT,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    action TEXT,
    table_name TEXT,
    record_count INTEGER,
    is_success BOOLEAN,
    message TEXT,
    device_info TEXT
);

-- 10. Bảng Cấu hình hệ thống (system_config)
CREATE TABLE IF NOT EXISTS public.system_config (
    config_key TEXT PRIMARY KEY,
    config_val TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================================
-- BẬT REALTIME CHO CÁC BẢNG TRỌNG YẾU (Để Desktop / PDA nhận event tức thì)
-- ==========================================================
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    CREATE PUBLICATION supabase_realtime;
  END IF;
END $$;

ALTER PUBLICATION supabase_realtime ADD TABLE public.items;
ALTER PUBLICATION supabase_realtime ADD TABLE public.pallets;
ALTER PUBLICATION supabase_realtime ADD TABLE public.inbound_orders;
ALTER PUBLICATION supabase_realtime ADD TABLE public.outbound_orders;
ALTER PUBLICATION supabase_realtime ADD TABLE public.locations;

-- ==========================================================
-- TẮT RLS HOẶC MỞ TOÀN QUYỀN TRUY CẬP CHO ANON/AUTHENTICATED TRONG GIAI ĐOẠN DEV
-- ==========================================================
ALTER TABLE public.products DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.locations DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.pallets DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.items DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.inbound_orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.inbound_order_details DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.outbound_orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.outbound_order_details DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.sync_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_config DISABLE ROW LEVEL SECURITY;
